# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  vars:
    vHome: /home/vagrant

  tasks:
    - name: Copy prod scripts to prod environment
      copy: src=../scripts dest=/home/vagrant/ mode=0777 # give full rights to user on this directory

    - name: Rename the scripts folder
      command: sh /home/vagrant/scripts/rename-scripts-folder.sh