# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  vars:
    vHome: /home/vagrant

  tasks:
    - name: Copy prod scripts to prod environment
      copy: src=../scripts dest=/home/vagrant/ mode=0777 # give full rights to user on this directory

    - name: Rename the scripts folder
      command: sh /home/vagrant/scripts/rename-scripts-folder.sh

    - name: Setup artefact repository
      command: sh /home/vagrant/prod-scripts/setup-artefact-repository.sh

    - name: Setup gitlab runner
      command: sh /home/vagrant/prod-scripts/setup-gitlab-runner.sh

    - name: Give gitlab runner user sudo privileges without password
      command: sh /home/vagrant/prod-scripts/gitlab-runner-sudo-nopasswd.sh

    - name: Create MySQL database e4l
      command: sh /home/vagrant/prod-scripts/create-mysql-database.sh

    - name: Setup nginx folder
      command: sh /home/vagrant/prod-scripts/setup-nginx-folder.sh

    - name: Setup nginx
      command: sh /home/vagrant/prod-scripts/setup-nginx.sh
